version: '3'
services:
  database:
    #location of Dockerfile
    build: ./data
  backend:
    build: ./APP
    #directory from docker
    volumes:
      - ./APP:/app/script
    ports:
      - "5000:5000"